import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import os
import time

# File path to the CSV generated by the C++ server
CSV_FILE = 'server_stats.csv'

# Setup the figure and subplots
fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
fig.suptitle('Server Performance Monitor')

def animate(i):
    if not os.path.exists(CSV_FILE):
        print(f"Waiting for {CSV_FILE}...")
        return

    try:
        # Read the last 60 entries to show a 1-minute window
        df = pd.read_csv(CSV_FILE, names=['Timestamp', 'PPS', 'Mbps'], header=0)
        
        if df.empty:
            return

        # Keep only the last 60 records for real-time view
        df = df.tail(60)

        x = range(len(df)) # Simple index for x-axis, or use df['Timestamp'] if formatted

        # Clear previous plots
        ax1.clear()
        ax2.clear()

        # Plot PPS
        ax1.plot(x, df['PPS'], label='PPS', color='blue')
        ax1.set_ylabel('Packets / Sec')
        ax1.legend(loc='upper left')
        ax1.grid(True)

        # Plot Bandwidth
        ax2.plot(x, df['Mbps'], label='Bandwidth (Mbps)', color='red')
        ax2.set_ylabel('Mbps')
        ax2.set_xlabel('Time (Last 60 seconds)')
        ax2.legend(loc='upper left')
        ax2.grid(True)

    except Exception as e:
        print(f"Error reading CSV: {e}")

# Update every 1000ms (1 second)
ani = animation.FuncAnimation(fig, animate, interval=1000)

plt.show()
